spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://60.205.254.22:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: liu134513


  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.liu: debug
  file:
    path: log/blog-dev.log
